### ISSUE TITLE
截图插件实例化时发出警告，无法启用截图功能

### ISSUE THREAD

**Issue by gouxiwen** [nashaofu/shortcut-capture#3]
WARNING: Textured window <AtomNSWindow: 0x7fa6e5cbcdf0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by gouxiwen** [comment]
> WARNING: Textured window <AtomNSWindow: 0x7fa6e5cbcdf0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by nashaofu** [comment]
怎么回事呀？

**Comment by gouxiwen** [comment]
我之前在开发环境无法启用截图功能，发现控制台有这个警告，以为是因为这个原因导致的，后来运行你的钉钉项目发现也有这个警告，但是截图功能正常，所以就关闭了这个问题。我尝试打包以后使用，结果是可以使用截图的（很奇怪），我发现截图页面打开以后没有快速退出功能，要截完图后点击确认或者取消才能退出，希望可以改进，插件写的很好，谢谢你！

**Comment by gouxiwen** [comment]
关于快速退出的问题，我发现实例调用$win.close()就可以啦，文档中没有说明
