### ISSUE TITLE
新版本，截图的窗口无法关闭。。一直是截图的状态

### ISSUE THREAD

**Issue by CQBoyBrand** [nashaofu/shortcut-capture#8]
点确认和取消都没反应。我电脑是mac

**Comment by nashaofu** [comment]
经确认是有这个问题，我会尽快修复

**Comment by CQBoyBrand** [comment]
谢谢🙏，

從我的 iPhone 傳送

**Comment by nashaofu** [comment]
已经发了新版本，我这边测试是可以了的，感谢反馈

**Comment by CQBoyBrand** [comment]
好的，我更新试下
重庆崽儿Brand
brandhuang@qq.com

**Comment by CQBoyBrand** [comment]
你好，新版本。还有一个问题。。。截完图后，程序坞和状态栏没有恢复正常。。需要鼠标移上去才会显示，离开又隐藏了，如图：
![image](https://user-images.githubusercontent.com/20539402/51536738-83132900-1e87-11e9-8a2d-49ee52adf09d.png)

**Comment by CQBoyBrand** [comment]
当我使用插件的软件为当前窗口的时候会这样，切换到其他软件会恢复正常，切换回这个软件又回变成这样

**Comment by CQBoyBrand** [comment]
clone下这个仓库的代码本地试了下，也有上面说的问题，建议修改下onhide方法，推出的时候，退出全屏，本地试了下，这样可以
```js

  /**
   * 绑定窗口隐藏事件
   */
  onHide () {
    ipcMain.on('ShortcutCapture::HIDE', (e, bounds) => {
      if (!this.$win) return
      this.$win.setSimpleFullScreen(false)
      this.$win.close()
      this.$win = null
    })
  }
```

**Comment by nashaofu** [comment]
是的，应该是这个方法

**Comment by CQBoyBrand** [comment]
> 是的，应该是这个方法

大佬什么时候方便更新下npm吗，哈哈，顺便问下。。能把隐藏窗口的事件暴露出来吗。方便处理键盘的esc退出截屏，现在好像调用不到onHide方法

**Comment by nashaofu** [comment]
可以考虑，今晚发一个版本

**Comment by nashaofu** [comment]
已经发了新版本
