### ISSUE TITLE
在electron 4.0.0调用shortcutCapture.shortcutCapture()方法无反应

### ISSUE THREAD

**Issue by betterRunner** [nashaofu/shortcut-capture#9]
博主您好，
clone了博主您的`dingtalk`的代码执行截图功能是ok的，说明我的电脑（win7,64）支持该截图功能
但在我的项目安装`shortcut-capture`则无反应，运行没有报错，按下'alt+ctl+a'后屏幕会闪一下然后没后跳出截图的界面。`dingtalk`使用的electron版本是2.0.15，我的项目使用eletron的版本是4.0.0，请问是否支持该版本？
谢谢

**Comment by nashaofu** [comment]
4.0的没有测试，我会在4.0的版本测试一下

**Comment by nashaofu** [comment]
我这边在mac os使用4.0是可以的，windows暂时没有电脑测试，感觉应该是没有问题才对

**Comment by betterRunner** [comment]
抱歉这么久才回复，

我用另一台电脑测试了windows，同时也测试了linux
应该都是以下的问题：
1. 在dev模式下，由于以下这个错误导致无法截图
`Not allowed to load local resource: file:///.../node_modules/electron/dist/resources/default_app.asar/node_modules/shortcut-capture/dist/renderer/index.html`
2. build打包运行的就可以

所以我遇到的问题应该是在dev模式的路径问题，请问你是在dev模式测试的还是build模式呢

**Comment by nashaofu** [comment]
你直接使用npm安装打包的就好了呀，如果你是要clone我的仓库去自己修改，那么直接运行命令`npm run dev`就好了。不是很清楚你为什么要使用dev模式，还有你是如何使用的，报错问题可以确定为[截图界面HTML URL问题](https://github.com/nashaofu/shortcut-capture/blob/90c03cd95ba495a855ca59b0fc53cb03cc3bab27/src/main/shortcut-capture.js#L62)

**Comment by betterRunner** [comment]
可能没有表述清楚，我说的dev模式是我工程的dev模式，我是直接使用你的npm包的，就是在我的项目的dev模式下你的包会报错，但是build打包就不会报错

**Comment by nashaofu** [comment]
![image](https://user-images.githubusercontent.com/19303058/52861500-93a87d80-316d-11e9-8b87-a73ad86f1d6a.png)
你可以手动指定一下截图界面加载的html文件，指向插件目录下的index.html就行了

**Comment by betterRunner** [comment]
好的，谢谢～
